---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: ap-southeast-1
    keyname: proxy
  tasks:
    - name: create key pair
      ec2_key:
        region: "{{ region }}"
        name: "{{ keyname }}"
      register: mykey

    - name: write to file
      copy: content="{{ mykey.key.private_key }}" dest="~/.ssh/{{ keyname }}.pem" mode=0600
#      copy: content="{{ mykey.key.private_key }}" dest="$PWD/{{ keyname }}.pem" mode=0600
      when: mykey.changed

